In [67]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/datacrab.txt", delimiter=' ')
cw = df.width
n = cw.size

def calculateExtremes(k):
    presicion = 0.1
    
    A = (np.diff([min(cw), max(cw)]) / k)[0]
    A = np.around(A, 1) + presicion

    L1 = min(cw) - 1/2 * presicion
    L = L1 + A * range(0, 11)
    
    return L

def calculateClassMark(L):
    return (L[1:L.size-1] + L[2:L.size]) / 2



1. Da el algoritmo para reproducir el proceso de generación de clases y sus marcas respectivo para el número de clases obtenido con la regla de la Scott en  Python.

In [72]:
AS = 3.5 * np.std(cw) * n**(-1/3)
k1 = np.ceil((np.diff([min(cw), max(cw)]) / AS)[0])

L = calculateExtremes(k1)
X = calculateClassMark(L)
X

array([22.9, 24.2, 25.5, 26.8, 28.1, 29.4, 30.7, 32. , 33.3])

2. Da el algoritmo para reproducir el proceso de generación de clases y sus marcas respectivo para el número de clases obtenido con la regla de la raíz en R o en Python.

In [69]:
k2 = np.ceil(np.sqrt(n))
L = calculateExtremes(k2)
X = calculateClassMark(L)
X

array([22.45, 23.45, 24.45, 25.45, 26.45, 27.45, 28.45, 29.45, 30.45])

3. Da el algoritmo para reproducir el proceso de generación de clases y sus marcas respectivo para el número de clases obtenido con la regla de la Sturges en R o en Python

In [74]:
k3 = np.ceil(1 + np.log2(n))

L = calculateExtremes(k3)
X = calculateClassMark(L)
X

array([23.2, 24.7, 26.2, 27.7, 29.2, 30.7, 32.2, 33.7, 35.2])

4. Da el algoritmo para reproducir el proceso de generación de clases y sus marcas respectivo para el número de clases obtenido con la regla de la  Freedman-Diaconis en R o en Python.

In [77]:
AFD = 2 * np.quantile(cw, 0.75) - np.quantile(cw, 0.25) * n**(-1/3)
k4 = np.ceil((np.diff([min(cw), max(cw)]) / AFD)[0])

L = calculateExtremes(k4)
X = calculateClassMark(L)
X

array([ 39.85,  52.45,  65.05,  77.65,  90.25, 102.85, 115.45, 128.05,
       140.65])