# Matrices
Vamos a usar la libreia numpy

In [2]:
row = [1, 2, 3]
row

[1, 2, 3]

In [3]:
col = [[1], [2], [3]]
col

[[1], [2], [3]]

In [4]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
M[1][1]

5

In [6]:
M[0]

[1, 2, 3]

In [7]:
2 * M

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
import numpy as np

In [11]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.shape(M)

(3, 3)

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [1, -1]])

In [16]:
A + B

array([[4, 2],
       [4, 3]])

In [17]:
A.dot(B) # Producto matricial

array([[ 5, -2],
       [13, -4]])

In [18]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [19]:
A.trace()

5

In [20]:
np.linalg.matrix_rank(A)

2

In [21]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

In [22]:
np.linalg.det(A)

-2.0000000000000004

In [23]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [25]:
# Matriz no invertible. No se puede hacer la inversa de una matriz cuadrada o una matriz cuyo rango sea menor 
# que su determinate
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
np.linalg.inv(X).dot(X)

LinAlgError: Singular matrix